### PR TITLE
Created a small uninstall script for those in need.

### PR DESCRIPTION
**Pull request by Tudorhc5**
Just a starting one, maybe it can be expanded upon.

### CODE REVIEW

**Comment by prplwtf** [comment]
Keeping it open for the time being so I have a bit of time to think about how I'd want to implement this into Blueprint.

**Comment by david1117dev** [comment]
Sounds like chatgpt code to me, but, after all, why should this be a problem. :)

**Comment by prplwtf** [comment]
> Sounds like chatgpt code to me, but, after all, why should this be a problem. :)

I'd say the opposite, if it were ChatGPT code, it would've capitalized "pterodactyl" in some code comments. It's just well-written code from what I can see.

**Comment by david1117dev** [comment]
Yeah, that's true, you're maybe right, but the "# Add more filenames as needed" made me think that's chatgpt

**Comment by Tudorhc5** [comment]
definetly got some parts from chatgpt, not worth writing them yourself, much easier to say what you want it to do then improve it.

**Comment by prplwtf** [comment]
Understandable.

**Comment by prplwtf** [comment]
I'm choosing to not merge this pull request. This PR appears to have been implemented in a third party tool already (growtoups/bp-utilities) and I don't really have a reason to include this in the framework directly. Additional feedback is welcome, but until someone comes up with a great way to implement this (which I haven't been able to find yet) this PR will remain closed.

**Pull request closed without merging**
