### PR TITLE
added location for components in server/terminal page

### PR DESCRIPTION
**Pull request by Gasuge**
4 new locations added

`Server:
  Terminal:
    AdditionalPowerButtons: ""
    BeforeInformation: ""
    AfterInformation: ""
    AdditionalConsole: ""`

### CODE REVIEW

**Comment by prplwtf** [comment]
Thanks for your contribution!

Could you please upload a screenshot with placeholder texts on all the component placements you added?

**Review by prplwtf — CHANGES_REQUESTED** [review]
What does `AdditionalConsole` exactly do? Might need to be renamed to something else as it might not be descriptive enough.

**Comment by Gasuge** [comment]
image

i renamed it

`AdditionalConsole ` -> `SendCommand`

**Comment by prplwtf** [comment]
Alright, that makes a bit more sense. What about `ConsoleCommandRow`? Might fit up a little bit better.

We basically got to nail these placement names as we can't have documenation for each and every one of them.

**Comment by Gasuge** [comment]
ok it's changed

**Review by prplwtf — APPROVED** [review]
Ready to merge.

**Comment by prplwtf** [comment]
I completely forgot I merged this! Once again thank you for your contribution, I've updated the docs to include your change in commit https://github.com/BlueprintFramework/web/commit/25109d54f2bef0fb5068688206f900db1039db2c.

**Pull request merged**
